Repository KU-Barrier-Free/KU-Barrier-Free-Android, pull requests merged in 2025-08, with the labels that each got.

#23 [Feat] API 연경환경 세팅 #22
  app/build.gradle.kts
  app/src/main/java/com/ganaljigi/KUBFApp.kt
  app/src/main/java/com/ganaljigi/kubf/data/di/ApiModule.kt
  app/src/main/java/com/ganaljigi/kubf/data/di/NetworkModule.kt
  app/src/main/java/com/ganaljigi/kubf/data/di/RepositoryModule.kt
  app/src/main/java/com/ganaljigi/kubf/data/remote/base/BaseResponse.kt
  app/src/main/java/com/ganaljigi/kubf/data/remote/service/BuildingService.kt
  app/src/main/java/com/ganaljigi/kubf/data/remote/service/HelperService.kt
  app/src/main/java/com/ganaljigi/kubf/data/remote/service/HomeService.kt
  app/src/main/java/com/ganaljigi/kubf/data/remote/service/RouteService.kt
  app/src/main/java/com/ganaljigi/kubf/dummy/data/repository/DummyRepository.kt
  app/src/main/java/com/ganaljigi/kubf/dummy/data/repositoryimpl/DummyRepositoryImpl.kt
  app/src/main/java/com/ganaljigi/kubf/dummy/data/response/DummyResponseDto.kt
  app/src/main/java/com/ganaljigi/kubf/dummy/data/service/DummyService.kt
  app/src/main/java/com/ganaljigi/kubf/dummy/di/DummyApiModule.kt
  app/src/main/java/com/ganaljigi/kubf/dummy/di/DummyRepositoryModule.kt
  app/src/main/java/com/ganaljigi/kubf/dummy/mapper/DummyMapper.kt
  app/src/main/java/com/ganaljigi/kubf/dummy/ui/dummy/DummyScreen.kt
  app/src/main/java/com/ganaljigi/kubf/dummy/ui/dummy/model/DummyUiState.kt
  app/src/main/java/com/ganaljigi/kubf/dummy/ui/dummy/viewmodel/DummyViewModel.kt
  gradle/libs.versions.toml
Labels: feat

#12 [Feat] Building Info UI 구현 #2
  app/src/main/java/com/ganaljigi/kubf/MainActivity.kt
  app/src/main/java/com/ganaljigi/kubf/data/dto/buildingdata/DoorData.kt
  app/src/main/java/com/ganaljigi/kubf/data/dto/buildingdata/Facility.kt
  app/src/main/java/com/ganaljigi/kubf/data/dto/buildingdata/FloorInfoData.kt
  app/src/main/java/com/ganaljigi/kubf/data/dto/buildingdata/NotesData.kt
  app/src/main/java/com/ganaljigi/kubf/data/dto/buildingdata/RoomData.kt
  app/src/main/java/com/ganaljigi/kubf/data/dto/buildingdata/TotalBuildingData.kt
  app/src/main/java/com/ganaljigi/kubf/data/dto/buildingdata/TotalFloorData.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/component/DoorComponent.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/component/FacilityComponent.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/component/FloorComponent.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/component/NoteComponent.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/component/RoomComponent.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/screen/BuildingInfoScreen.kt
  app/src/main/res/drawable/ic_feature_cafe.xml
  app/src/main/res/drawable/ic_feature_conv.xml
  app/src/main/res/drawable/ic_feature_itser.xml
  app/src/main/res/drawable/ic_feature_kcube.xml
  app/src/main/res/drawable/ic_feature_park.xml
  app/src/main/res/drawable/ic_feature_print.xml
  app/src/main/res/drawable/ic_feature_rest.xml
Labels: feat, 하늘

#28 [Feat] Helper ViewModel #27
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ganaljigi/kubf/data/di/ApiModule.kt
  app/src/main/java/com/ganaljigi/kubf/data/di/NetworkModule.kt
  app/src/main/java/com/ganaljigi/kubf/data/remote/service/HelperService.kt
  app/src/main/java/com/ganaljigi/kubf/navigation/MainNavHost.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/component/FloorComponent.kt
  app/src/main/java/com/ganaljigi/kubf/ui/helper/component/notice/NoticeComponent.kt
  app/src/main/java/com/ganaljigi/kubf/ui/helper/di/HelperRepositoryModule.kt
  app/src/main/java/com/ganaljigi/kubf/ui/helper/mapper/HelperMapper.kt
  app/src/main/java/com/ganaljigi/kubf/ui/helper/repository/HelperRepository.kt
  app/src/main/java/com/ganaljigi/kubf/ui/helper/repositoryimpl/HelperRepositoryImpl.kt
  app/src/main/java/com/ganaljigi/kubf/ui/helper/response/HelperResponseDto.kt
  app/src/main/java/com/ganaljigi/kubf/ui/helper/screen/HelperScreen.kt
  app/src/main/java/com/ganaljigi/kubf/ui/helper/viewmodel/HelperUiState.kt
  app/src/main/java/com/ganaljigi/kubf/ui/helper/viewmodel/HelperViewModel.kt
  gradle/libs.versions.toml
Labels: feat, 재인

#29 [Feat] BuildingInfoScreen-Searching
  app/src/main/java/com/ganaljigi/kubf/data/di/BuildingInfoRepositoryModule.kt
  app/src/main/java/com/ganaljigi/kubf/data/di/NetworkModule.kt
  app/src/main/java/com/ganaljigi/kubf/data/dto/buildingdata/DoorData.kt
  app/src/main/java/com/ganaljigi/kubf/data/dto/buildingdata/FloorInfoData.kt
  app/src/main/java/com/ganaljigi/kubf/data/dto/buildingdata/NotesData.kt
  app/src/main/java/com/ganaljigi/kubf/data/dto/buildingdata/RoomData.kt
  app/src/main/java/com/ganaljigi/kubf/data/dto/buildingdata/TotalBuildingData.kt
  app/src/main/java/com/ganaljigi/kubf/data/dto/buildingdata/TotalFloorData.kt
  app/src/main/java/com/ganaljigi/kubf/data/mock/DummySpacesJson.kt
  app/src/main/java/com/ganaljigi/kubf/data/remote/service/BuildingService.kt
  app/src/main/java/com/ganaljigi/kubf/data/repository/BuildingInfoRepository.kt
  app/src/main/java/com/ganaljigi/kubf/data/repository/BuildingInfoRepositoryImpl.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/component/DoorComponent.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/component/FacilityComponent.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/component/FloorComponent.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/component/NoteComponent.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/component/RoomComponent.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/component/SearchComponent.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/mapper/BuildingMapper.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/model/BuildingInfo.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/model/Door.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/model/Facility.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/model/FloorInfo.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/model/Note.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/model/Room.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/model/RoomSearchResult.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/model/TotalFloor.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/response/BuildingResponseDto.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/screen/BuildingInfoScreen.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/viewmodel/BuildingUIState.kt
  app/src/main/java/com/ganaljigi/kubf/ui/buildinginfo/viewmodel/BuildingViewModel.kt
Labels: feat, 하늘
